# Generated by Django 5.2.9 on 2025-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='house_status',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='renovation_details',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='selected_items',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='total_sqft',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='sqft',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='total_amount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
