# Generated by Django 5.2.9 on 2025-12-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0002_remove_product_category_delete_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='floorplans/')),
            ],
        ),
    ]
