# Generated by Django 5.2.9 on 2025-12-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0003_floorplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='kitchen/')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
