# Generated by Django 5.2.9 on 2025-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0004_kitchenitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenitem',
            name='kitchen_shape',
            field=models.CharField(choices=[('STRAIGHT KITCHEN', 'Straight Kitchen'), ('L SHAPE KITCHEN', 'L Shape Kitchen'), ('U SHAPE KITCHEN', 'U Shape Kitchen')], default='STRAIGHT KITCHEN', max_length=50),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='material',
            field=models.CharField(choices=[('PLY WITH LAM', 'Ply with Lam'), ('PLY WITH ACRYLIC', 'Ply with Acrylic'), ('PLY WITH VENEER', 'Ply with Veneer'), ('WPC WITH LAM', 'WPC with Lam')], default='PLY WITH LAM', max_length=50),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='size',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='specification',
            field=models.TextField(default='Standard specification'),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='unit_type',
            field=models.CharField(choices=[('BOTTOM UNIT', 'Bottom Unit'), ('WALL UNIT', 'Wall Unit')], default='BOTTOM UNIT', max_length=50),
        ),
    ]
