# Generated by Django 5.2.9 on 2025-12-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0005_kitchenitem_kitchen_shape_kitchenitem_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TV Unit', 'TV Unit'), ('Washing Unit', 'Washing Unit'), ('Mirror', 'Mirror'), ('Partition', 'Partition'), ('Break Fast Table', 'Break Fast Table'), ('BedCOT', 'BedCOT'), ('Head Board', 'Head Board'), ('Wall Panel', 'Wall Panel'), ('Texture Paint', 'Texture Paint'), ('Side Table', 'Side Table'), ('Wardrobe', 'Wardrobe'), ('Dressing', 'Dressing'), ('Vanity', 'Vanity')], max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specification', models.TextField(blank=True, default='Standard Specification')),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sqft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='total_amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kitchen/'),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='kitchen_shape',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='material',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='unit_type',
            field=models.CharField(max_length=50),
        ),
    ]
