# Generated by Django 5.2.9 on 2025-12-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0006_generalmodule_kitchenaccessory_alter_enquiry_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralModule',
        ),
        migrations.DeleteModel(
            name='KitchenAccessory',
        ),
    ]
