# Generated by Django 5.2.9 on 2025-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0007_delete_generalmodule_delete_kitchenaccessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_type', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('specification', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='modules/')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories/')),
            ],
        ),
        migrations.RemoveField(
            model_name='kitchenitem',
            name='size',
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='depth',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='height',
            field=models.IntegerField(default=850),
        ),
        migrations.AddField(
            model_name='kitchenitem',
            name='length',
            field=models.IntegerField(default=3000),
        ),
    ]
