# Generated by Django 5.2.9 on 2025-12-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0008_generalmodule_kitchenaccessory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalmodule',
            name='size',
        ),
        migrations.AddField(
            model_name='generalmodule',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalmodule',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generalmodule',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='generalmodule',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='generalmodule',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kitchenitem',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
