# Generated by Django 5.2.9 on 2026-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0009_remove_generalmodule_size_generalmodule_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenaccessory',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitchenaccessory',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitchenaccessory',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kitchenaccessory',
            name='specification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
