# Generated by Django 5.2.9 on 2026-01-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0010_kitchenaccessory_depth_kitchenaccessory_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
