# Generated by Django 5.2.9 on 2026-01-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0011_enquiry_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='EnquiryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='interior.enquiry')),
            ],
        ),
    ]
